### ISSUE TITLE
import tab panels dynamically

### ISSUE THREAD

**Issue by G3root** [G3root/readme-generator#3]
make tab panels import's dynamic in [PreviewColumnTab](https://github.com/G3root/readme-generator/blob/main/src/components/editor/PreviewColumnTab/PreviewColumnTab.tsx) component.

for reference [next.js dynamic import ](https://nextjs.org/docs/advanced-features/dynamic-import)

**Comment by WVAviator** [comment]
I can do this for you if you'd like
